// AUTOGENERATED FROM GPU PROGRAMS DESCRIPTION

// ../gpu//solid.vert
var shader_solid_vert =
	"#version 300 es\n" +
	"\n" +
	"precision highp float;\n" +
	"\n" +
	"in vec3 vtxPos;\n" +
	"in vec3 vtxNrm;\n" +
	"in vec3 vtxRGB;\n" +
	"in vec2 vtxTex;\n" +
	"\n" +
	"uniform mat4 prmWorld;\n" +
	"uniform mat4 prmViewProj;\n" +
	"\n" +
	"out vec3 pixPos;\n" +
	"out vec3 pixNrm;\n" +
	"out vec3 pixRGB;\n" +
	"out vec2 pixTex;\n" +
	"\n" +
	"void main() {\n" +
	"\tmat4 wm = prmWorld;\n" +
	"\tpixPos = (vec4(vtxPos, 1.0) * wm).xyz;\n" +
	"\tpixNrm = (vec4(vtxNrm, 0.0) * wm).xyz;\n" +
	"\tpixRGB = vtxRGB;\n" +
	"\tpixTex = vtxTex;\n" +
	"\tgl_Position = vec4(pixPos, 1.0) * prmViewProj;\n" +
	"}\n" +
"";

// ../gpu//unlit.frag
var shader_unlit_frag =
	"#version 300 es\n" +
	"\n" +
	"precision highp float;\n" +
	"\n" +
	"in vec3 pixPos;\n" +
	"in vec3 pixNrm;\n" +
	"in vec3 pixRGB;\n" +
	"in vec2 pixTex;\n" +
	"\n" +
	"out vec4 outClr;\n" +
	"\n" +
	"uniform vec3 prmBaseColor;\n" +
	"\n" +
	"//uniform sampler2D smpBase;\n" +
	"\n" +
	"void main() {\n" +
	"\tvec3 clr = pixRGB * prmBaseColor;\n" +
	"\toutClr = vec4(clr, 1.0f);\n" +
	"}\n" +
	"\n" +
"";

// ../gpu//solid_unlit.prog
var solid_unlit_prog = {
	 vs:{ name: "shader_solid_vert", src:shader_solid_vert },
	 fs:{ name: "shader_unlit_frag", src:shader_unlit_frag },
	 attrs:
		["Pos","Nrm","RGB","Tex"],
	 uniforms:
		["World","ViewProj","BaseColor"],
	 samplers:
		[],
}
