// AUTOGENERATED FROM GPU PROGRAMS DESCRIPTION

// ../gpu/solid.vert
var shader_solid_vert =
	"precision highp float;\n" +
	"\n" +
	"attribute vec3 vtxPos;\n" +
	"attribute vec3 vtxNrm;\n" +
	"attribute vec3 vtxRGB;\n" +
	"attribute vec2 vtxTex;\n" +
	"\n" +
	"uniform mat4 prmWorld;\n" +
	"uniform mat4 prmViewProj;\n" +
	"\n" +
	"varying vec3 pixPos;\n" +
	"varying vec3 pixNrm;\n" +
	"varying vec3 pixRGB;\n" +
	"varying vec2 pixTex;\n" +
	"\n" +
	"void main() {\n" +
	"\tmat4 wm = prmWorld;\n" +
	"\tpixPos = (vec4(vtxPos, 1.0) * wm).xyz;\n" +
	"\tpixNrm = (vec4(vtxNrm, 0.0) * wm).xyz;\n" +
	"\tpixRGB = vtxRGB;\n" +
	"\tpixTex = vtxTex;\n" +
	"\tgl_Position = vec4(pixPos, 1.0) * prmViewProj;\n" +
	"}\n" +
"";

// ../gpu/unlit.frag
var shader_unlit_frag =
	"precision highp float;\n" +
	"\n" +
	"varying vec3 pixPos;\n" +
	"varying vec3 pixNrm;\n" +
	"varying vec3 pixRGB;\n" +
	"varying vec2 pixTex;\n" +
	"\n" +
	"uniform vec3 prmBaseColor;\n" +
	"\n" +
	"uniform sampler2D smpBase;\n" +
	"\n" +
	"void main() {\n" +
	"\tvec4 tex = texture2D(smpBase, pixTex);\n" +
	"\ttex.rgb *= prmBaseColor;\n" +
	"\tvec3 clr = tex.rgb * pixRGB;\n" +
	"\tgl_FragColor = vec4(clr, tex.a);\n" +
	"}\n" +
	"\n" +
"";

// ../gpu/solid_unlit.prog
var solid_unlit_prog = {
	 vs:{ name: "shader_solid_vert", src:shader_solid_vert },
	 fs:{ name: "shader_unlit_frag", src:shader_unlit_frag },
	 attrs:
		["Pos","Nrm","RGB","Tex"],
	 uniforms:
		["World","ViewProj","BaseColor"],
	 samplers:
		["Base"],
}
